[package]
name = "vsdelta"
version = "0.1.0"
authors = ["github@fadedbee.com"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
sha2 = "0.9"

[build-dependencies]
built = "0.4"